const cachedBrandLogos = localStorage.getItem("brandLogos")

const rawBrandLogos = {
  Bentley: "/images/bentley.png",
  Mitsuoka: "/images/mitsuoka.png",
  Mitsubishi: "/images/mitsubishi.png",
  McLaren: "/images/mclaren.png",
  Mazda: "/images/mazda.png",
  Maybach: "/images/maybach.png",
  Maserati: "/images/maserati.png",
  Lincoln: "/images/lincoln.png",
  Renault: "/images/renault.png",
  "Rolls-Royce": "/images/rolls-royce.png",
  Lotus: "/images/lotus.png",
  Rover: "/images/rover.png",
  Lexus: "/images/lexus.png",
  Lamborghini: "/images/lamborghini.png",
  Dodge: "/images/dodge.png",
  Daihatsu: "/images/daihatsu.png",
  Nissan: "/images/nissan.png",
  "Land Rover": "/images/landrover.png",
  Volvo: "/images/volvo.png",
  Mini: "/images/mini.png",
  Volkswagen: "/images/volkswagen.png",
  Audi: "/images/audi.png",
  "Mercedes-Benz": "/images/mercedes.png",
  BMW: "/images/bmw.png",
  Hyundai: "/images/hyundai.png",
  KIA: "/images/kia.png",
  Genesis: "/images/genesis.png",
  "Chevrolet (Korea)": "/images/chevrolet.png",
  Chevrolet: "/images/chevrolet.png",
  "Renault Korea (Samsung)": "/images/renaultkorea.png",
  "KG Mobility (SsangYong)": "/images/kg.png",
  Daewoo: "/images/daewoo.png",
  Bugatti: "/images/bugatti.png",
  Buick: "/images/buick.png",
  SAAB: "/images/saab.png",
  Scion: "/images/scion.png",
  Smart: "/images/smart.png",
  Subaru: "/images/subaru.png",
  Suzuki: "/images/suzuki.png",
  Opel: "/images/opel.png",
  Oldsmobile: "/images/oldsmobile.png",
  Iveco: "/images/iveco.png",
  Isuzu: "/images/isuzu.png",
  Infiniti: "/images/infiniti.png",
  Jaguar: "/images/jaguar.png",
  Jeep: "/images/jeep.png",
  Zidou: "/images/zhidou.png",
  Geely: "/images/geely.png",
  Cadillac: "/images/cadillac.png",
  Chrysler: "/images/chrysler.png",
  Tesla: "/images/tesla.png",
  Toyota: "/images/toyota.png",
  Ferrari: "/images/ferrari.png",
  Ford: "/images/ford.png",
  Foton: "/images/foton.png",
  Pontiac: "/images/pontiac.png",
  Peugeot: "/images/peugeot.png",
  Fiat: "/images/fiat.png",
  Hummer: "/images/hummer.png",
  GMC: "/images/gmc.png",
  Polestar: "/images/polestar.png",
  BYD: "/images/byd.png",
  Citroën: "/images/citroen.png",
  "Alfa Romeo": "/images/alfaromeo.png",
  "Aston Martin": "/images/astonmartin.png",
  Acura: "/images/acura.png",
  Honda: "/images/honda.png",
  Porsche: "/images/porsche.png",
}

const brandLogos = cachedBrandLogos
  ? JSON.parse(cachedBrandLogos)
  : rawBrandLogos

if (!cachedBrandLogos) {
  localStorage.setItem("brandLogos", JSON.stringify(rawBrandLogos))
}

export default brandLogos
